/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m6uf2act8;

import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author jaade
 */
public class InterfazInsertar extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInsertar
     */
    public InterfazInsertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnAfegirVehicle = new javax.swing.JButton();
        jBtnInsertarPropietari = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonFVE = new javax.swing.JRadioButton();
        jTextFieldFVM = new javax.swing.JTextField();
        jTextFieldFVP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFPP = new javax.swing.JTextField();
        jLabelEstat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Formulari Vehicle");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Formulari Propietari");

        jBtnAfegirVehicle.setText("Insertar Vehicle");
        jBtnAfegirVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAfegirVehicleActionPerformed(evt);
            }
        });

        jBtnInsertarPropietari.setText("Insertar Propietari");
        jBtnInsertarPropietari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInsertarPropietariActionPerformed(evt);
            }
        });

        jBtnSalir.setText("Sortir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Model: ");

        jLabel4.setText("Nom Propietari:");

        jRadioButtonFVE.setText("Electric");
        jRadioButtonFVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFVEActionPerformed(evt);
            }
        });

        jLabel5.setText("Nom Propietari: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonFVE)
                    .addComponent(jTextFieldFVM, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFVP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jBtnAfegirVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnInsertarPropietari, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldFPP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelEstat, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabelEstat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonFVE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAfegirVehicle)
                    .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnInsertarPropietari))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAfegirVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAfegirVehicleActionPerformed
        // Open a database connection
        // (create a new database if it doesn't exist yet):
        EntityManagerFactory emf
                = Persistence.createEntityManagerFactory("$objectdb/db/p2.odb");
        EntityManager em = emf.createEntityManager();

        // Store 1000 Point objects in the database:
        em.getTransaction().begin();

        // Si algun texfield esta buit mostrem missatge de error
        if (jTextFieldFVM.getText().equals("") || jTextFieldFVP.getText().equals("")) {
            
            jLabelEstat.setText("ERROR, Omple els camps de vehicle");
            
        // Sino creem l'objecte i el guardem a la db
        } else {

            propietari p = new propietari(jTextFieldFVP.getText());
            em.persist(p);

            // Si es electric
            if (jRadioButtonFVE.isSelected()) {
                vehicle v = new vehicle(jTextFieldFVM.getText(), p, new Date(), true);
                em.persist(v);
            // Si no es electric
            } else {
                vehicle v = new vehicle(jTextFieldFVM.getText(), p, new Date(), false);
                em.persist(v);
            }  
            jLabelEstat.setText("vehicle insertat amb exit");
        }

        em.getTransaction().commit();
        
        // Close the database connection:
        em.close();
        emf.close();
    }//GEN-LAST:event_jBtnAfegirVehicleActionPerformed

    private void jRadioButtonFVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFVEActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFVEActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        interfaz.setVisible(true);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnInsertarPropietariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInsertarPropietariActionPerformed
        // Open a database connection
        // (create a new database if it doesn't exist yet):
        EntityManagerFactory emf
                = Persistence.createEntityManagerFactory("$objectdb/db/p2.odb");
        EntityManager em = emf.createEntityManager();

        // Store 1000 Point objects in the database:
        em.getTransaction().begin();

        // Si algun texfield esta buit mostrem missatge de error
        if (jTextFieldFPP.getText().equals("")) {
            
            jLabelEstat.setText("ERROR, Omple els camps del propietari");
            
        // Sino creem l'objecte i el guardem a la db
        } else {

            propietari p = new propietari(jTextFieldFVP.getText());
            em.persist(p);

            jLabelEstat.setText("Propietari insertat amb exit");
        }

        em.getTransaction().commit();
        
        // Close the database connection:
        em.close();
        emf.close();
    }//GEN-LAST:event_jBtnInsertarPropietariActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAfegirVehicle;
    private javax.swing.JButton jBtnInsertarPropietari;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEstat;
    private javax.swing.JRadioButton jRadioButtonFVE;
    private javax.swing.JTextField jTextFieldFPP;
    private javax.swing.JTextField jTextFieldFVM;
    private javax.swing.JTextField jTextFieldFVP;
    // End of variables declaration//GEN-END:variables
}
